iml-wg/HEPML-LivingReview

.github/workflows/ci.yml, .gitignore, JHEP.bst, Makefile
Add testing with CI through GitHub Actions that verifies the README generation and that the LaTeX can be built with `latexmk`. Deployment can be added in a follow up PR.
Suggested squash message:
```
* Add .gitignore, missing JHEP.bst, and Makefile
* Add CI through GitHub Actions
```
=> Add Makefile and CI

.github/workflows/docs.yml, README.md, make_md.py
Using GitHub Actions, on push events to `master` (so when a branch is merged) build the docs and then deploy them to the `gh-pages` branch for rendering on GitHub. Additionally, add to the README generation a link to the built PDF as the `README` will become the `index.html` on the website: https://bnachman.github.io/HEP-ML-LivingReview
[![download](https://img.shields.io/badge/download-review-blue.svg)](https://bnachman.github.io/HEP-ML-LivingReview/review/hepml-review.pdf)
```
* Add docs deployment GitHub Actions workflow
- Deploy README and built PDF to GitHub pages website
* Add download link badge to README
```
=> ci: Add deployment of the docs on master

.github/workflows/ci.yml, .github/workflows/docs.yml, HEPML.tex, footnote_build_info.py
Taking a page from @kratsg, this PR adds a Python script that runs during CI that takes information from the state of the Git repository and the environmental variables that are set by GitHub Actions to amend `jheppub.sty` to include as a footnote on the title page
```
Built Month DD, YYYY from commit_SHA
```
where `Month DD, YYYY` is hyperlinked to the GitHub Actions workflow that built the PDF and `commit_SHA` is hyperlinked to the commit on GitHub that the repo was at when the docs were built. This makes it immediately clear to any reader when the review was last updated.
```
* Add Python script to patch build info footnote into jheppub.sty
* Add script to steps in CI
* Remove redundant inclusion of hyperref
```
=> feat: Add build date and commit footnote to CI builds

.github/workflows/ci.yml, .github/workflows/docs.yml
In an effort to provide higher fidelity testing to the normal workflow, [use the Docker image for the step instead of a GitHub Action](https://github.com/xu-cheng/latex-action/issues/30#issuecomment-623893988), allowing for the `Makefile` to be used directly.
```
* Use Docker image instead of GitHub Action to allow for Makefile to be used
- Override the image ENTRYPOINT to install make and run
```
=> ci: Use Docker image directly to run Make

HEPML.bib, HEPML.tex, README.md
Move [Probing heavy ion collisions using quark and gluon jet substructure](https://inspirehep.net/literature/1659306) by Yang-Ting Chien and @rkunnawa to its chronological position given publication date on INSPIRE of 2018-03-09.
=> fix: Move probing heavy ion collisions to chronological placement

HEPML.bib, HEPML.tex, README.md
- Resolves #13
- Resolves #11 
Synchronize BibTeX file with the state of HEPML-Resources BibTeX file (at https://github.com/iml-wg/HEP-ML-Resources/commit/226ed83ba0654d2a628f9b67e3f13bf627c74847). This effectively is just moving over https://github.com/iml-wg/HEP-ML-Resources/pull/75: "[Use of a Generalized Energy Mover’s Distance in the Search for Rare Phenomena at Colliders](https://inspirehep.net/literature/1791839) by M. C. Romao, @nfcastro, J. Milhano, R. Pedro, and T. Vale
```
* Migrate HEPML-Resources BibTeX file
* Remove trailing whitespace
```
=> chore: Migrate all of HEPML-Resources BibTeX file

HEPML.bib, README.md
Add DOI to BibTeX entry for [_Identification of heavy, energetic, hadronically decaying particles using machine-learning techniques_](https://inspirehep.net/literature/1791648) CMS paper.
this does not change the readme unless #22 is merged with displaying the doi
=> feat: Add DOI for Identification of heavy, energetic, hadronically decaying particles paper

HEPML.bib, HEPML.tex, README.md
- add CMS ggHbb which uses the deep double-b tagger
=> paper: Add CMS ggHbb paper with deep double-b tagger

HEPML.bib, HEPML.tex, README.md
Revert PR #31. This was my fault for not doing a better review to check the content of the paper before accepting it.
Contributions are helpful and welcome, but the goal of the project is to provide an updating list of references of "modern machine learning as applied to particle physics."
```
* Remove ML only paper with no physics tie in
* Revert PR #31
```
=> revert: Remove ML only paper

CONTRIBUTING.md
Update the `CONTRIBUTING.md` thanks to some very helpful discussion with @juliagonski.
```
* Add forking step to PR workflow instructions
* Add FAQ on scope of papers in review
```
=> docs: Add forking to PR workflow instructions

HEPML.tex, README.md, jheppub.sty, make_md.py
Hello,
@matthewfeickert started [this issue](https://github.com/iml-wg/HEPML-LivingReview/issues/14) some time ago and I wanted to revisit it.  This request is significant and so I have made it a MR instead of automatically updating it (as I have been for the latest papers).  Here is the proposal:
1. Each heading has a small bit of explanation.  This appears in the .tex and .pdf versions, but not the markdown (but only because I did not have enough time to make that happen - we can revisit that in the future).
2. This version will be posted to arXiv.  This will improve visibility and linking (e.g. it will also automatically be on Inspire).  I would propose that we post new versions to arXiv periodically (perhaps ~1-2 times per year?)
3. I have listed the author in the .tex and .pdf as …
=> feat: Add section heading information and corresponding authors

.pre-commit-config.yaml, footnote_build_info.py, make_md.py
To leverage existing maintenance infrastructure (that has been used extensively in Scikit-HEP) add pre-commit hooks defined in `.pre-commit-config.yaml` that run `pyupgrade` on the Python files changed in a commit if a `pre-commit` installation is found in the environment.
Additionally [activate pre-commit.ci](https://results.pre-commit.ci/repo/github/258003247) to run pre-commit on every PR and automatically pushback changes if needed.
```
* Add pyupgrade as pre-commit hook
- Runs if if pre-commit is installed in environment
* Apply pre-commit.ci to automatically help maintain code compliance with modern Python 3
* Apply pyupgrade --py37-plus to codebase
```
=> test: Add pre-commit hooks

.github/workflows/ci.yml, .github/workflows/docs.yml
Use the [texlive-action GitHub Action](https://github.com/xu-cheng/texlive-action) over the [`xucheng/texlive-full` Docker image](https://github.com/xu-cheng/latex-docker).
```
* Use xu-cheng/texlive-action v1 over xucheng/texlive-full Docker image
* Update Python runtime to Python 3.8
* Update CI workflow name
```
=> ci: Use texlive-action GitHub Action over texlive-full Docker image

HEPML.bib, README.md
As a temporary fix for Issue #49, this PR simply applies quotes (`"`) around the BibTeX fields `title` and `eprint` in the `.bib` file. Quoting allows for the fields to be properly parsed, but a follow up PR should address Issue #49 by making the parsing more robust.
```
* Apply quotes around BibTeX 'title' and 'eprint' BibTeX fields to allow for proper parsing
- Temporary fix 
- c.f. https://github.com/iml-wg/HEPML-LivingReview/issues/49
```
=> fix: Quote title and eprint BibTex fields in .bib file

HEPML.bib, HEPML.tex, README.md
Add [Unveiling CP property of top-Higgs coupling with graph neural networks at the LHC](https://inspirehep.net/literature/1714710) and [Probing stop pair production at the LHC with graph neural networks](https://inspirehep.net/literature/1683688).
```
* Add reference for 'Unveiling CP property of top-Higgs coupling with graph neural networks at the LHC'
- c.f. https://arxiv.org/abs/1901.05627
* Add reference for 'Probing stop pair production at the LHC with graph neural networks'
- c.f. https://arxiv.org/abs/1807.09088
* Add links to Graphs section
```
=> paper: Add GNN papers for top-Higgs coupling and stop pair production

HEPML.bib, HEPML.tex, README.md
Add [Using neural networks for efficient evaluation of high multiplicity scattering amplitudes](https://inspirehep.net/literature/1781330).
```
* Add reference to 'Using neural networks for efficient evaluation of high multiplicity scattering amplitudes'
- c.f. https://arxiv.org/abs/2002.07516
* Add link to sections: Matrix elements
```
=> paper: Add NNs for efficient evaluation of high multiplicity scattering amplitudes

HEPML.bib, HEPML.tex, README.md
Add [Resurrecting bb¯h with kinematic shapes](https://inspirehep.net/literature/1833995).
```
* Add reference to 'Resurrecting bb¯h with kinematic shapes'
- c.f. https://arxiv.org/abs/2011.13945
* Add link to sections: physics-inspired basis, feature ranking, interpretability
```
Resurrecting $b\bar{b}h$ with kinematic shapes (https://arxiv.org/abs/2011.13945) addresses the question of measuring b-Yukawa from the bbh process at HL-LHC and FCC. We use an interpretable machine learning framework with a physics-inspired basis and use Shapley values for understanding variable importance and correlations.
Authors: Christophe Grojean, @talismanbrandi, and Zhuoni Qian
=> paper: Resurrecting bbh with kinematic shapes

.github/workflows/ci.yml, .github/workflows/docs.yml, .pre-commit-config.yaml, HEPML.bib, README.md, footnote_build_info.py, make_md.py, requirements.txt
Fix regression in 2c3d565633304a6b72a13c404af066a86f6a3300 by adding the required dependencies and installing them in the CI workflow.
```
* Add required dependencies in requirements.txt
* Update and apply pre-commit hooks
- Add pre-commit and isort
* Install required dependencies in the CI/CD workflows
```
=> fix: Install Python requirements in CI

README.md, make_md.py
This issue is related to closed issue #45, as the issue still seems to still appear when inproceedings items are added. A fix in `make_md.py` was added to not look for "booktitle" when looking for "title" 
In addition, I added a fix for adding URLs when an eprint is also available. The reason to do so if for proceedings without DOI, which is common in AI/ML conferences.
```
* Use 'title' over 'booktitle' to avoid incorrect tiles for nproceedings entires
- Amends ae13060 (c.f. Issue #45)
* Add support for allowing URLs to be displayed if they exist in entries
- It is common in AI/ML conferences for proceedings to be published without DOIs but with URLs
```
=> fix: Use 'title' over 'booktitle' and allow for URLs in entries

HEPML.bib, HEPML.tex, README.md
Add the reference of 4.0 paper containing a description of the
hyperoprimization and fitting methodology as well as other potentially
relevant issues such as validation tests or decorrelation.
Add a reference to the NNPDF code, which has been newly made open source
and contains all the data and code required to reproduce the PDF sets,
as well as ancillary analysis.
Closes #80.
=> Add references to the NNPDF code and results

.github/workflows/ci.yml, .github/workflows/docs.yml
Use the latest CPython available by using `3.x` where `x` will resolve to the newest CPython available in https://github.com/actions/setup-python GitHub Action.
```
* Update actions/checkout from v2 to v3
* Update actions/setup-python from v1 to v3
* Use latest CPython available to actions/setup-python for testing
```
=> ci: Use latest CPython for tests

make_md.py, requirements.txt
Neither `PyYAML` or the `json` module are used at all, so remove their imports and remove `PyYAML` from `requirements.txt`
```
* Remove unused imports of PyYAML and json
* Remove unused PyYAML dependencies from requirements.txt
* Update requests compatible release versions to v2.x
```
=> chore: Remove unused PyYAML and json dependencies

HEPML.bib, HEPML.tex, README.md
add our proceedings about multi-step ML (vCHEP2021).
Add reference for [Event Classification with Multi-step Machine Learning](https://arxiv.org/abs/2106.02301) by Masahiko Saito, Tomoe Kishimoto, Yuya Kaneta, Taichi Itoh, Yoshiaki Umeda, Junichi Tanaka, Yutaro Iiyama, Ryu Sawada, Koji Terashi which appear in proceedings for ICHEP 2021.
```
* Add 'Event Classification with Multi-step Machine Learning' which appear
in proceedings for ICHEP 2021.
- c.f. https://doi.org/10.1051/epjconf/202125103036
```
=> paper: Add Event Classification with Multi-step Machine Learning proceedings

README.md, make_md.py
This was causing the category $H\rightarrow b\bar{b}$ to break.
```
* Allow for } to exist inside of `\textbf{}` and to be properly extracted.
```
=> fix: Properly select } in \textbf argument

HEPML.bib, docs/recent.md
Currently on recent.md we have July, June, July due to an entry out of place based on the month key (though the arxiv month differs).
=> fix bib entry position - arxiv says july, month june
